spring.application.name=ship_odms

# 서버 포트 설정
server.port=8088

# SQLite DB 설정
spring.datasource.url=jdbc:sqlite:ship_odms.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA & Hibernate 설정 (앱 시작 시 항상 DB 초기화)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
