from pydantic import BaseModel, Field
from typing import Optional, List

class Ship(BaseModel):
    id: int = Field(None, description="PK")
    imo_number: str = Field(..., description="IMO0140: Ship IMO number")
    ship_name: Optional[str] = Field(..., description="IMO0142: Ship name")
    ship_type: Optional[str] = Field(..., description="IMO0160: Ship type, coded")
    ship_type_marpol: Optional[str] = Field(..., description="IMO0859: Ship type MARPOL Annex VI, coded")
    flag_state: Optional[str] = Field(..., description="IMO0138: Ship flag State, coded")
    mmsi: Optional[str] = Field(..., description="IMO0326: Ship MMSI number")
    call_sign: Optional[str] = Field(..., description="IMO0136: Ship call sign")
    registry_port: Optional[str] = Field(..., description="IMO0147: Ship registry port, coded")

class YearPerformanceReport(BaseModel):
    id: int = Field(None, description="PK")
    ship_id: int = Field(..., description="FK")
    total_gfi_annually: Optional[float] = Field(None, description="IMO0854: Fuel, Total GHG intensity (IMO), annually [gCO2eq/MJ]")

class Voyage(BaseModel):
    id: int = Field(None, description="PK")
    ship_id: int = Field(..., description="FK")
    year_report_id: int = Field(None, description="FK")
    voyage_number: Optional[str] = Field(None, description="IMO0191: Voyage number")
    trade_service_id: Optional[str] = Field(None, description="IMO0536: Trade service identifier")
    gfi_per_voyage: Optional[float] = Field(None, description="IMO0855: Fuel, GHG intensity (IMO), per voyage [gCO2eq/MJ]")
    inbound_port_jurisdiction: Optional[str] = Field(None, description="IMO0856: Inbound Port jurisdiction, coded")
    outbound_port_jurisdiction: Optional[str] = Field(None, description="IMO0857: Outbound Port jurisdiction, coded")

class PortCall(BaseModel):
    id: int = Field(None, description="PK")
    voyage_id: int = Field(..., description="FK")
    port_arrival: Optional[str] = Field(None, description="IMO0108: Port of arrival, coded")
    port_departure: Optional[str] = Field(None, description="IMO0111: Port of departure, coded")
    port_ata: Optional[str] = Field(None, description="IMO0063: Date and time of arrival - actual")
    port_atd: Optional[str] = Field(None, description="IMO0065: Date and time of departure - actual")

class WeatherDetails(BaseModel):
    id: int = Field(None, description="PK")
    report_id: int = Field(..., description="FK")
    sea_state: Optional[int] = Field(None, description="IMO0363: State of the sea, coded")
    wind_force: Optional[int] = Field(None, description="IMO0625: Wind force")
    wind_speed: Optional[int] = Field(None, description="IMO0359: Wind speed, coded")
    wind_dir: Optional[int] = Field(None, description="IMO0360: Wind direction, coded")
    wind_dir_relative: Optional[float] = Field(None, description="IMO0626: Wind direction, estimated, relative")
    wind_dir_true: Optional[float] = Field(None, description="IMO0627: Wind direction, estimated, true")
    air_temperature: Optional[float] = Field(None, description="IMO0628: Air temperature")
    atmospheric_pressure: Optional[int] = Field(None, description="IMO0629: Atmospheric pressure")
    sea_dir_relative: Optional[int] = Field(None, description="IMO0630: Sea direction, relative")
    sea_dir_true: Optional[int] = Field(None, description="IMO0631: Sea direction, true")
    sea_height: Optional[int] = Field(None, description="IMO0632: Sea height")
    swell_dir_relative: Optional[int] = Field(None, description="IMO0633: Swell direction, relative")
    swell_dir_true: Optional[int] = Field(None, description="IMO0634: Swell direction, true")
    swell_height: Optional[int] = Field(None, description="IMO0635: Swell height")
    ocean_dir_relative: Optional[int] = Field(None, description="IMO0636: Ocean current direction, relative")
    ocean_dir_true: Optional[int] = Field(None, description="IMO0637: Ocean current direction, true")
    ocean_dir_weather_provider: Optional[int] = Field(None, description="IMO0638: Ocean current direction, weather provider")

class CargoOnboard(BaseModel):
    id: int = Field(None, description="PK")
    report_id: int = Field(None, description="FK")
    number_containers: Optional[int] = Field(None, description="IMO0650: Total numbers of containers, TEU")
    number_full_container: Optional[int] = Field(None, description="IMO0651: Total number of full containers, TEU")
    number_full_reefer_containers: Optional[int] = Field(None, description="IMO0652: Total number of full reefer containers in use, TEU")
    number_vehicles_onboard: Optional[int] = Field(None, description="IMO0653: Total number of vehicles onboard, CEU")
    number_crew: Optional[int] = Field(None, description="IMO0086: Number of crew")
    number_passengers: Optional[int] = Field(None, description="IMO0087: Number of passengers")
    number_chilled_20ft_reefer_containers: Optional[int] = Field(None, description="IMO0864: Number of chilled 20 ft reefer containers")
    number_chilled_40ft_reefer_containers: Optional[int] = Field(None, description="IMO0865: Number of chilled 40 ft reefer containers")
    number_frozen_20ft_reefer_containers: Optional[int] = Field(None, description="IMO0866: Number of frozen 20 ft reefer containers")
    number_frozen_40ft_reefer_containers: Optional[int] = Field(None, description="IMO0867: Number of frozen 40 ft reefer containers")
    goods_description: Optional[str] = Field(None, description="IMO0022: Cargo item description of goods")
    gross_volume: Optional[float] = Field(None, description="IMO0023: Cargo item gross volume")
    gross_weight: Optional[float] = Field(None, description="IMO0024: Cargo item gross weight")
    bl_ref_id: Optional[str] = Field(None, description="IMO0734: Bill of Lading reference identifier")
    bl_issued_date: Optional[str] = Field(None, description="IMO0738: Bill of Lading issued date")

class ElectricConsumption(BaseModel):
    id: int = Field(None, description="PK")
    report_id: int = Field(None, description="FK")
    power_boiler: Optional[float] = Field(None, description="IMO0646: Boiler electricity consumption [kwh]")
    power_generator: Optional[float] = Field(None, description="IMO0647: Generator production [kwh]")
    power_offset: Optional[float] = Field(None, description="IMO0648: Offset electricity consumption [kwh]")
    power_plant: Optional[float] = Field(None, description="IMO0649: Power consumption for plant [kwh]")
    energy_cargo_cooling: Optional[float] = Field(None, description="IMO0868: Electrical work generated for Cargo Cooling [kwh]")
    energy_discharge_pump: Optional[float] = Field(None, description="IMO0869: Electrical work generated for discharge pump [kwh]")
    energy_reefer_containers: Optional[float] = Field(None, description="IMO0870: Electrical work generated for reefer containers [kwh]")
    energy_onshore_power_supply: Optional[float] = Field(None, description="IMO0871: Electrical work received from On Shore Power Supply [kwh]")
    energy_zero_emissions_tech: Optional[float] = Field(None, description="IMO0872: Electrical work received from zero emissions technologies [kwh]")
    fuel_type_cargo_cooling: Optional[int] = Field(None, description="IMO0873: Fuel type used for electrical work generated for cargo cooling, coded")
    fuel_type_discharge_pump: Optional[int] = Field(None, description="IMO0874: Fuel type used for electrical work generated for discharge pump, coded")
    fuel_type_reefer_container: Optional[int] = Field(None, description="IMO0875: Fuel type used for electrical work generated for reefers container, coded")
    sfoc_cargo_cooling: Optional[float] = Field(None, description="IMO0876: Specific fuel oil consumption for electrical work generated for cargo cooling [g/kWh]")
    sfoc_discharge_pump: Optional[float] = Field(None, description="IMO0877: Specific fuel oil consumption for electrical work generated for discharge pump [g/kWh]")
    sfoc_cargo_reefers: Optional[float] = Field(None, description="IMO0878: Specific fuel oil consumption for electrical work generated for cargo reefers [g/kWh]")

class FocFuelType(BaseModel):
    id: int = Field(None, description="PK")
    fuel_consumption_id: int = Field(None, description="FK")
    foc_main_engine: Optional[float] = Field(None, description="IMO0893: Fuel consumed, by Main Engine")
    foc_diesel_electric_propulsion: Optional[float] = Field(None, description="IMO0894: Fuel consumed, by Diesel Electric Propulsion")
    foc_diesel_generator: Optional[float] = Field(None, description="IMO0895: Fuel consumed, by Diesel Generator")
    foc_auxiliary_boiler: Optional[float] = Field(None, description="IMO0896: Fuel consumed, by Auxiliary Boiler")
    foc_auxiliary_engine: Optional[float] = Field(None, description="IMO0897: Fuel consumed, by Auxiliary Engine")
    foc_cargo_cooling: Optional[float] = Field(None, description="IMO0898: Fuel consumed, by Cargo Cooling")
    foc_cargo_heating: Optional[float] = Field(None, description="IMO0899: Fuel consumed, by Cargo Heating")
    foc_diesel_power_packs: Optional[float] = Field(None, description="IMO0900: Fuel consumed, by Diesel Power Packs")
    foc_dirty_petroleum_products_cargo_pump: Optional[float] = Field(None, description="IMO0901: Fuel consumed, by Dirty Petroleum Products Cargo Pump")
    foc_discharge_pump: Optional[float] = Field(None, description="IMO0902: Fuel consumed, by Discharge Pump")
    foc_dp_operations: Optional[float] = Field(None, description="IMO0903: Fuel consumed, by DP Operations")
    foc_electrical_power_generation: Optional[float] = Field(None, description="IMO0904: Fuel consumed, by Electrical Power Generation")
    foc_incinerator: Optional[float] = Field(None, description="IMO0905: Fuel consumed, by Incinerator")
    foc_inert_gas_generators_gcus: Optional[float] = Field(None, description="IMO0910: Fuel consumed, by Inert Gas Generators/GCUs")
    foc_other_fuel_consuming_devices: Optional[float] = Field(None, description="IMO0911: Fuel consumed, by Other Fuel Consuming Devices")
    foc_reefer_containers: Optional[float] = Field(None, description="IMO0912: Fuel consumed, by Reefer Containers")
    foc_shuttle_tanker_operations: Optional[float] = Field(None, description="IMO0913: Fuel consumed, by Shuttle Tanker Operations")
    foc_sts_operations: Optional[float] = Field(None, description="IMO0906: Fuel consumed, by STS Operations")

class FocConsumerType(BaseModel):
    id: int = Field(None, description="PK")
    fuel_consumption_id: int = Field(None, description="FK")
    fuel_used_main_engine: Optional[int] = Field(None, description="IMO0914: Fuel type used by Main Engine, coded")
    fuel_consumed_main_engine: Optional[float] = Field(None, description="IMO0915: Fuel consumed by Main Engine, by fuel type")
    fuel_used_diesel_electric_propulsion: Optional[int] = Field(None, description="IMO0916: Fuel type used by Diesel Electric Propulsion, coded")
    fuel_consumed_diesel_electric_propulsion: Optional[float] = Field(None, description="IMO0917: Fuel consumed by Diesel Electric Propulsion, by fuel type")
    fuel_used_diesel_generator: Optional[int] = Field(None, description="IMO0918: Fuel type used by Diesel Generator, coded")
    fuel_consumed_diesel_generator: Optional[float] = Field(None, description="IMO0919: Fuel consumed by Diesel Generator, by fuel type")
    fuel_used_auxiliary_boiler: Optional[int] = Field(None, description="IMO0920: Fuel type used by Auxiliary Boiler, coded")
    fuel_consumed_auxiliary_boiler: Optional[float] = Field(None, description="IMO0921: Fuel consumed by Auxiliary Boiler, by fuel type")
    fuel_used_auxiliary_engine: Optional[int] = Field(None, description="IMO0922: Fuel type used by Auxiliary Engine, coded")
    fuel_consumed_auxiliary_engine: Optional[float] = Field(None, description="IMO0923: Fuel consumed by Auxiliary Engine, by fuel type")
    fuel_used_cargo_cooling: Optional[int] = Field(None, description="IMO0924: Fuel type used by Cargo Cooling, coded")
    fuel_consumed_cargo_cooling: Optional[float] = Field(None, description="IMO0925: Fuel consumed by Cargo Cooling, by fuel type")
    fuel_used_cargo_heating: Optional[int] = Field(None, description="IMO0926: Fuel type used by Cargo Heating, coded")
    fuel_consumed_cargo_heating: Optional[float] = Field(None, description="IMO0927: Fuel consumed by Cargo Heating, by fuel type")
    fuel_used_diesel_power_packs: Optional[int] = Field(None, description="IMO0928: Fuel type used by Diesel Power Packs, coded")
    fuel_consumed_diesel_power_packs: Optional[float] = Field(None, description="IMO0929: Fuel consumed by Diesel Power Packs, by fuel type")
    fuel_used_dirty_petroleum_products_cargo_pump: Optional[int] = Field(None, description="IMO0930: Fuel type used by Dirty Petroleum Products Cargo Pump, coded")
    fuel_consumed_dirty_petroleum_products_cargo_pump: Optional[float] = Field(None, description="IMO0931: Fuel consumed by Dirty Petroleum Products Cargo Pump, by fuel type")
    fuel_used_discharge_pump: Optional[int] = Field(None, description="IMO0932: Fuel type used by Discharge Pump, coded")
    fuel_consumed_discharge_pump: Optional[float] = Field(None, description="IMO0933: Fuel consumed by Discharge Pump, by fuel type")
    fuel_used_dp_operations: Optional[int] = Field(None, description="IMO0934: Fuel type used by DP Operations, coded")
    fuel_consumed_dp_operations: Optional[float] = Field(None, description="IMO0935: Fuel consumed by DP Operations, by fuel type")
    fuel_used_electrical_power_generation: Optional[int] = Field(None, description="IMO0936: Fuel type used by Electrical Power Generation, coded")
    fuel_consumed_electrical_power_generation: Optional[float] = Field(None, description="IMO0937: Fuel consumed by Electrical Power Generation, by fuel type")
    fuel_used_incinerator: Optional[int] = Field(None, description="IMO0938: Fuel type used by Incinerator, coded")
    fuel_consumed_incinerator: Optional[float] = Field(None, description="IMO0939: Fuel consumed by Incinerator, by fuel type")
    fuel_used_inert_gas_generators_gcus: Optional[int] = Field(None, description="IMO0940: Fuel type used by Inert Gas Generators/GCUs, coded")
    fuel_consumed_inert_gas_generators_gcus: Optional[float] = Field(None, description="IMO0941: Fuel consumed by Inert Gas Generators/GCUs, by fuel type")
    fuel_used_other_fuel_consuming_devices: Optional[int] = Field(None, description="IMO0944: Fuel type used by Other Fuel Consuming Devices, coded")
    fuel_consumed_other_fuel_consuming_devices: Optional[float] = Field(None, description="IMO0945: Fuel consumed by Other Fuel Consuming Devices, by fuel type")
    fuel_used_reefer_containers: Optional[int] = Field(None, description="IMO0946: Fuel type used by Reefer Containers, coded")
    fuel_consumed_reefer_containers: Optional[float] = Field(None, description="IMO0947: Fuel consumed by Reefer Containers, by fuel type")
    fuel_used_shuttle_tanker_operations: Optional[int] = Field(None, description="IMO0948: Fuel type used by Shuttle Tanker Operations, coded")
    fuel_consumed_shuttle_tanker_operations: Optional[float] = Field(None, description="IMO0949: Fuel consumed by Shuttle Tanker Operations, by fuel type")
    fuel_used_sts_operations: Optional[int] = Field(None, description="IMO0940: Fuel type used by STS Operations, coded")
    fuel_consumed_sts_operations: Optional[float] = Field(None, description="IMO0942: Fuel consumed by STS Operations, by fuel type")

class FuelConsumption(BaseModel):
    id: int = Field(None, description="PK")
    report_id: int = Field(None, description="FK")
    fuel_type: Optional[int] = Field(None, description="IMO0654: Fuel type, coded")
    fuel_type_trade_name: Optional[str] = Field(None, description="IMO0680: Fuel type trade name, coded")
    bdn_number: Optional[str] = Field(None, description="IMO0655: Bunker delivery note number")
    bdn_datetime: Optional[str] = Field(None, description="IMO0656: Bunker delivery date time")
    fuel_bunker_received: Optional[float] = Field(None, description="IMO0657: Fuel bunker received")
    fuel_mass: Optional[float] = Field(None, description="IMO0658: Fuel, mass")
    fuel_density: Optional[int] = Field(None, description="IMO0659: Fuel, density")
    fuel_sulphur_content: Optional[int] = Field(None, description="IMO0660: Fuel, sulphur content")
    fuel_viscosity: Optional[int] = Field(None, description="IMO0661: Fuel, viscosity")
    fuel_water_content: Optional[int] = Field(None, description="IMO0662: Fuel, water content")
    fuel_hhv: Optional[int] = Field(None, description="IMO0663: Fuel, higher heating value")
    fuel_lfv: Optional[int] = Field(None, description="IMO0664: Fuel, lower heating value")
    fuel_grade: Optional[int] = Field(None, description="IMO0665: Fuel grade, coded")
    fuel_bunker_port: Optional[str] = Field(None, description="IMO0666: Fuel bunker port, coded")
    fuel_bunker_port_name: Optional[str] = Field(None, description="IMO0667: Fuel bunker port name")
    co2_emission: Optional[float] = Field(None, description="IMO0670: CO2 emission")
    total_fuel_quantity_consumed: Optional[float] = Field(None, description="IMO0671: Total fuel quantity consumed")
    fuel_quantity_rob: Optional[float] = Field(None, description="IMO0672: Fuel quantity ROB")
    sludge_rob: Optional[float] = Field(None, description="IMO0673: Sludge ROB")
    fuel_lcv_report: Optional[str] = Field(None, description="IMO0674: Fuel LCV report")
    fuel_lcv: Optional[float] = Field(None, description="IMO0675: Fuel LCV")
    fuel_pos_ref: Optional[str] = Field(None, description="IMO0676: Fuel POS reference")
    ch4_cf: Optional[float] = Field(None, description="IMO0677: CH4 conversion factor")
    n2o_cf: Optional[float] = Field(None, description="IMO0678: N2O conversion factor")
    fresh_water_bunkered: Optional[float] = Field(None, description="IMO0681: Fresh water bunkered")
    fresh_water_produced: Optional[float] = Field(None, description="IMO0682: Fresh water produced")
    fresh_water_consumed: Optional[float] = Field(None, description="IMO0683: Fresh water consumed")
    technical_water_produced: Optional[float] = Field(None, description="IMO0684: Technical water produced")
    technical_water_consumed: Optional[float] = Field(None, description="IMO0685: Technical water consumed")
    wash_water_consumed: Optional[float] = Field(None, description="IMO0686: Wash water consumed")
    fresh_water_rob: Optional[float] = Field(None, description="IMO0687: Fresh water ROB")
    clo_rob: Optional[float] = Field(None, description="IMO0678: Cylinder lube oil, ROB")
    clo_feed_rate: Optional[float] = Field(None, description="IMO0679: Cylinder lube oil, feed rate")
    clo_consumption: Optional[float] = Field(None, description="IMO0679: Cylinder lube oil, consumption")
    clo_received: Optional[float] = Field(None, description="IMO0679: Cylinder lube oil, received")
    foc_fuel_type: List[FocFuelType] = Field(default_factory=list, description="연료별 소비량")
    foc_consumer_type: List[FocConsumerType] = Field(default_factory=list, description="소비원별 소비량")

class MeasuredCarbonDioxide(BaseModel):
    id: int = Field(None, description="PK")
    report_id: int = Field(None, description="FK")
    total_co2eq: Optional[float] = Field(None, description="IMO0880: Total CO2 equivalent [tCO2eq]")
    percentage_co2_emitted_at_sea: Optional[float] = Field(None, description="IMO0881: Percentage CO2 emitted at sea [%]")
    total_co2: Optional[float] = Field(None, description="IMO0882: Total CO2 [tCO2]")
    total_co2eq_captured: Optional[float] = Field(None, description="IMO0883: Total CO2eq captured [tCO2eq]")
    total_ch4: Optional[float] = Field(None, description="IMO0884: Total CH4 [tCH4]")
    total_ch4_to_co2: Optional[float] = Field(None, description="IMO0885: Total CH4 converted to CO2 [tCH4]")
    total_n2o: Optional[float] = Field(None, description="IMO0886: Total N2O [tN2O]")
    total_n2o_to_co2: Optional[float] = Field(None, description="IMO0890: Total N2O converted to CO2 [tN2O]")

class PerformanceReport(BaseModel):
    id: int = Field(None, description="PK")
    voyage_id: int = Field(None, description="FK")
    voyage_leg: Optional[str] = Field(None, description="IMO0605: Voyage leg identifier")
    event_type: Optional[str] = Field(None, description="IMO0597: Event type, coded")
    operation_type: Optional[str] = Field(None, description="IMO0598: Operation type, coded")
    elapsed_time: Optional[float] = Field(None, description="IMO0600: Elapsed time")
    report_type: Optional[str] = Field(None, description="IMO0879: Performance report type, coded")
    report_datetime: Optional[str] = Field(None, description="IMO0603: Ship reporting date time")
    latitude: Optional[float] = Field(None, description="IMO0601: Ship position when reporting, latitude")
    longitude: Optional[float] = Field(None, description="IMO0602: Ship position when reporting, longitude")
    distance_through_water: Optional[float] = Field(None, description="IMO0612: Distance through water [nm]")
    distance_over_ground: Optional[float] = Field(None, description="IMO0613: Distance over ground [nm]")
    distance_sailed_in_ice: Optional[float] = Field(None, description="IMO0614: Distance sailed in ice [nm]")
    distance_to_next_port: Optional[float] = Field(None, description="IMO0615: Distance to next port [nm]")
    laden_indicator: Optional[bool] = Field(None, description="IMO0860: Laden indicator")
    distance_excluded: Optional[float] = Field(None, description="IMO0861: Distance excluded [nm]")
    off_hire_reasons: Optional[str] = Field(None, description="IMO0862: Off hire Reasons")
    ship_draught: Optional[float] = Field(None, description="IMO0357: Ship draught")
    draught_forward: Optional[float] = Field(None, description="IMO0621: Draught forward")
    draught_aft: Optional[float] = Field(None, description="IMO0622: Draught aft")
    speed_over_ground: Optional[float] = Field(None, description="IMO0333: Speed over ground")
    speed_through_water: Optional[float] = Field(None, description="IMO0616: Speed through water")
    speed_propeller: Optional[float] = Field(None, description="IMO0617: Speed propeller")
    speed_projected: Optional[float] = Field(None, description="IMO0618: Speed projected")
    speed_order: Optional[float] = Field(None, description="IMO0619: Speed order")
    course_over_ground: Optional[float] = Field(None, description="IMO0332: Course over ground")
    ship_true_heading: Optional[float] = Field(None, description="IMO0620: Ship true heading")
    weather_details: List[WeatherDetails] = Field(default_factory=list, description="IMO0605_weather: 기상 정보")
    cargo_onboard: List[CargoOnboard] = Field(default_factory=list, description="IMO0605_cargo: 적재 화물 정보")
    electric_consumption: List[ElectricConsumption] = Field(default_factory=list, description="IMO0605_consumption: 전기 소비 정보")
    fuel_consumption: List[FuelConsumption] = Field(default_factory=list, description="IMO0605_consumption: 연료 소비 정보")
    measured_carbon_dioxide: List[MeasuredCarbonDioxide] = Field(default_factory=list, description="IMO0605_emissions: 탄소 배출 정보")
