// <auto-generated>
#nullable enable
// 이 파일은 openapi-types.ts를 기반으로 자동 변환되었습니다.
// 2026-05-05 기준. 필요시 partial class로 분리 가능.
using System;
using System.Collections.Generic;

namespace ship_odms.Models
{
    public class Ship
    {
        public int Id { get; set; }
        public string ImoNumber { get; set; }
        public string? ShipName { get; set; } = null;
        public string? ShipType { get; set; } = null;
        public string? ShipTypeMarpol { get; set; } = null;
        public string? FlagState { get; set; } = null;
        public string? Mmsi { get; set; } = null;
        public string? CallSign { get; set; } = null;
        public string? RegistryPort { get; set; } = null;
    }

    public class YearPerformanceReport
    {
        public int Id { get; set; }
        public int ShipId { get; set; }
        public double? TotalGfiAnnually { get; set; }
    }

    public class Voyage
    {
        public int Id { get; set; }
        public int ShipId { get; set; }
        public int YearReportId { get; set; }
        public string? VoyageNumber { get; set; } = null;
        public string? TradeServiceId { get; set; } = null;
        public double? GfiPerVoyage { get; set; } = null;
        public string? InboundPortJurisdiction { get; set; } = null;
        public string? OutboundPortJurisdiction { get; set; } = null;
    }


    public class PortCall
    {
        public int Id { get; set; }
        public int VoyageId { get; set; }
        public int ShipId { get; set; } // 추가
        public string? PortArrival { get; set; } = null;
        public string? PortDeparture { get; set; } = null;
        public string? PortAta { get; set; } = null;
        public string? PortAtd { get; set; } = null;
        public int PortCallId { get; set; } // 추가
    }

    public class WeatherDetails
    {
        public int Id { get; set; }
        [System.Text.Json.Serialization.JsonPropertyName("report_id")]
        public int ReportId { get; set; }
        public int? SeaState { get; set; }
        public int? WindForce { get; set; }
        public int? WindSpeed { get; set; }
        public int? WindDir { get; set; }
        public int? WindDirRelative { get; set; }
        public int? WindDirTrue { get; set; }
        public int? AirTemperature { get; set; }
        public double? AtmosphericPressure { get; set; }
        public int? SeaDirRelative { get; set; }
        public int? SeaDirTrue { get; set; }
        public int? SeaHeight { get; set; }
        public int? SwellDirRelative { get; set; }
        public int? SwellDirTrue { get; set; }
        public int? SwellHeight { get; set; }
        public int? OceanDirRelative { get; set; }
        public int? OceanDirTrue { get; set; }
        public int? OceanDirWeatherProvider { get; set; }
    }

    public class CargoOnboard
    {
        public int Id { get; set; }
        [System.Text.Json.Serialization.JsonPropertyName("report_id")]
        public int ReportId { get; set; }
        public int? NumberContainers { get; set; }
        public int? NumberFullContainer { get; set; }
        public int? NumberFullReeferContainers { get; set; }
        public int? NumberVehiclesOnboard { get; set; }
        public int? NumberCrew { get; set; }
        public int? NumberPassengers { get; set; }
        public int? NumberChilled20ftReeferContainers { get; set; }
        public int? NumberChilled40ftReeferContainers { get; set; }
        public int? NumberFrozen20ftReeferContainers { get; set; }
        public int? NumberFrozen40ftReeferContainers { get; set; }
        public double? GrossVolume { get; set; }
        public double? GrossWeight { get; set; }
            public string? GoodsDescription { get; set; } = null;
            public string? BlRefId { get; set; } = null;
            public string? BlIssuedDate { get; set; } = null;
    }

    public class ElectricConsumption
    {
        public int Id { get; set; }
        [System.Text.Json.Serialization.JsonPropertyName("report_id")]
        public int ReportId { get; set; }
        public double? PowerBoiler { get; set; }
        public double? PowerGenerator { get; set; }
        public double? PowerOffset { get; set; }
        public double? PowerPlant { get; set; }
        public double? EnergyCargoCooling { get; set; }
        public double? EnergyDischargePump { get; set; }
        public double? EnergyReeferContainers { get; set; }
        public double? EnergyOnshorePowerSupply { get; set; }
        public double? EnergyZeroEmissionsTech { get; set; }
        public double? FuelTypeCargoCooling { get; set; }
        public double? FuelTypeDischargePump { get; set; }
        public double? FuelTypeReeferContainer { get; set; }
        public double? SfocCargoCooling { get; set; }
        public double? SfocDischargePump { get; set; }
        public double? SfocCargoReefers { get; set; }
    }

    public class FocFuelType
    {
        public int Id { get; set; }
        public int FuelConsumptionId { get; set; }
        public double? FocMainEngine { get; set; }
        public double? FocDieselElectricPropulsion { get; set; }
        public double? FocDieselGenerator { get; set; }
        public double? FocAuxiliaryBoiler { get; set; }
        public double? FocAuxiliaryEngine { get; set; }
        public double? FocCargoCooling { get; set; }
        public double? FocCargoHeating { get; set; }
        public double? FocDieselPowerPacks { get; set; }
        public double? FocDirtyPetroleumProductsCargoPump { get; set; }
        public double? FocDischargePump { get; set; }
        public double? FocDpOperations { get; set; }
        public double? FocElectricalPowerGeneration { get; set; }
        public double? FocIncinerator { get; set; }
        public double? FocInertGasGeneratorsGcus { get; set; }
        public double? FocOtherFuelConsumingDevices { get; set; }
        public double? FocReeferContainers { get; set; }
        public double? FocShuttleTankerOperations { get; set; }
        public double? FocStsOperations { get; set; }
    }

    public class FocConsumerType
    {
        public int Id { get; set; }
        public int FuelConsumptionId { get; set; }
        public double? FuelUsedMainEngine { get; set; }
        public double? FuelConsumedMainEngine { get; set; }
        public double? FuelUsedDieselElectricPropulsion { get; set; }
        public double? FuelConsumedDieselElectricPropulsion { get; set; }
        public double? FuelUsedDieselGenerator { get; set; }
        public double? FuelConsumedDieselGenerator { get; set; }
        public double? FuelUsedAuxiliaryBoiler { get; set; }
        public double? FuelConsumedAuxiliaryBoiler { get; set; }
        public double? FuelUsedAuxiliaryEngine { get; set; }
        public double? FuelConsumedAuxiliaryEngine { get; set; }
        public double? FuelUsedCargoCooling { get; set; }
        public double? FuelConsumedCargoCooling { get; set; }
        public double? FuelUsedCargoHeating { get; set; }
        public double? FuelConsumedCargoHeating { get; set; }
        public double? FuelUsedDieselPowerPacks { get; set; }
        public double? FuelConsumedDieselPowerPacks { get; set; }
        public double? FuelUsedDirtyPetroleumProductsCargoPump { get; set; }
        public double? FuelConsumedDirtyPetroleumProductsCargoPump { get; set; }
        public double? FuelUsedDischargePump { get; set; }
        public double? FuelConsumedDischargePump { get; set; }
        public double? FuelUsedDpOperations { get; set; }
        public double? FuelConsumedDpOperations { get; set; }
        public double? FuelUsedElectricalPowerGeneration { get; set; }
        public double? FuelConsumedElectricalPowerGeneration { get; set; }
        public double? FuelUsedIncinerator { get; set; }
        public double? FuelConsumedIncinerator { get; set; }
        public double? FuelUsedInertGasGeneratorsGcus { get; set; }
        public double? FuelConsumedInertGasGeneratorsGcus { get; set; }
        public double? FuelUsedOtherFuelConsumingDevices { get; set; }
        public double? FuelConsumedOtherFuelConsumingDevices { get; set; }
        public double? FuelUsedReeferContainers { get; set; }
        public double? FuelConsumedReeferContainers { get; set; }
        public double? FuelUsedShuttleTankerOperations { get; set; }
        public double? FuelConsumedShuttleTankerOperations { get; set; }
        public double? FuelUsedStsOperations { get; set; }
        public double? FuelConsumedStsOperations { get; set; }
    }

    public class FuelConsumption
    {
        public int Id { get; set; }
        [System.Text.Json.Serialization.JsonPropertyName("report_id")]
        public int ReportId { get; set; }
        public int? FuelType { get; set; }
        public string? FuelTypeTradeName { get; set; } = null;
        public string? BdnNumber { get; set; } = null;
        public string? BdnDatetime { get; set; } = null;
        public double? FuelBunkerReceived { get; set; }
        public double? FuelMass { get; set; }
        public double? FuelDensity { get; set; }
        public double? FuelSulphurContent { get; set; }
        public double? FuelViscosity { get; set; }
        public double? FuelWaterContent { get; set; }
        public double? FuelHhv { get; set; }
        public double? FuelLfv { get; set; }
        public double? FuelGrade { get; set; }
        public string? FuelBunkerPort { get; set; } = null;
        public string? FuelBunkerPortName { get; set; } = null;
        public double? Co2Emission { get; set; }
        public double? TotalFuelQuantityConsumed { get; set; }
        public double? FuelQuantityRob { get; set; }
        public double? SludgeRob { get; set; }
        public string? FuelLcvReport { get; set; } = null;
        public double? FuelLcv { get; set; }
        public string? FuelPosRef { get; set; } = null;
        public double? Ch4Cf { get; set; }
        public double? N2oCf { get; set; }
        public double? FreshWaterBunkered { get; set; }
        public double? FreshWaterProduced { get; set; }
        public double? FreshWaterConsumed { get; set; }
        public double? TechnicalWaterProduced { get; set; }
        public double? TechnicalWaterConsumed { get; set; }
        public double? WashWaterConsumed { get; set; }
        public double? FreshWaterRob { get; set; }
        public double? CloRob { get; set; }
        public double? CloFeedRate { get; set; }
        public double? CloConsumption { get; set; }
        public double? CloReceived { get; set; }
        public List<FocFuelType>? FocFuelType { get; set; } = null;
        public List<FocConsumerType>? FocConsumerType { get; set; } = null;
    }

    public class MeasuredCarbonDioxide
    {
        public int Id { get; set; }
        [System.Text.Json.Serialization.JsonPropertyName("report_id")]
        public int ReportId { get; set; }
        public double? TotalCo2eq { get; set; }
        public double? PercentageCo2EmittedAtSea { get; set; }
        public double? TotalCo2 { get; set; }
        public double? TotalCo2eqCaptured { get; set; }
        public double? TotalCh4 { get; set; }
        public double? TotalCh4ToCo2 { get; set; }
        public double? TotalN2o { get; set; }
        public double? TotalN2oToCo2 { get; set; }
    }

    public class PerformanceReport
    {
        public int Id { get; set; }
        public int VoyageId { get; set; }
        public int? ShipId { get; set; } // 추가
        public int? PortCallId { get; set; } // 추가
        public int? Year { get; set; } // 추가
        public DateTime? CreatedAt { get; set; } // 추가
        public DateTime? UpdatedAt { get; set; } // 추가
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public double? DistanceThroughWater { get; set; }
        public double? DistanceOverGround { get; set; }
        public double? DistanceSailedInIce { get; set; }
        public double? DistanceToNextPort { get; set; }
        public bool? LadenIndicator { get; set; }
        public double? DistanceExcluded { get; set; }
        public string? OffHireReasons { get; set; } = null;
        public double? ShipDraught { get; set; }
        public double? DraughtForward { get; set; }
        public double? DraughtAft { get; set; }
        public double? SpeedOverGround { get; set; }
        public double? SpeedThroughWater { get; set; }
        public double? SpeedPropeller { get; set; }
        public double? SpeedProjected { get; set; }
        public double? SpeedOrder { get; set; }
        public double? CourseOverGround { get; set; }
        public double? ShipTrueHeading { get; set; }
        public List<WeatherDetails>? WeatherDetails { get; set; } = null;
        public List<CargoOnboard>? CargoOnboard { get; set; } = null;
        public List<ElectricConsumption>? ElectricConsumption { get; set; } = null;
        public List<FuelConsumption>? FuelConsumption { get; set; } = null;
        public List<MeasuredCarbonDioxide>? MeasuredCarbonDioxide { get; set; } = null;
        public string? Content { get; set; } = null;
        public string? VoyageLeg { get; set; } = null;
        public string? EventType { get; set; } = null;
        public string? OperationType { get; set; } = null;
        public double? ElapsedTime { get; set; }
        public string? ReportType { get; set; } = null;
        public string? ReportDatetime { get; set; } = null;
    }
}
